'use client';

import { useState } from 'react';

interface AIReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: any;
  attackInfo: any;
}

export default function AIReportModal({ isOpen, onClose, analysis, attackInfo }: AIReportModalProps) {
  if (!isOpen || !analysis) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm">
      <div className="bg-gray-900 border border-gray-700 rounded-lg max-w-4xl max-h-[90vh] overflow-y-auto p-6 m-4">
        {/* Header */}
        <div className="flex justify-between items-start mb-6">
          <div>
            <h2 className="text-2xl font-bold text-white mb-2">
              🤖 AI Attack Analysis
            </h2>
            <p className="text-gray-400 text-sm">
              {attackInfo.source.city}, {attackInfo.source.country} → {attackInfo.target.region}
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-white text-2xl"
          >
            ✕
          </button>
        </div>

        {/* Attack Details */}
        <div className="bg-gray-800/50 rounded-lg p-4 mb-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            <div>
              <div className="text-gray-400">Attack Type</div>
              <div className="text-white font-semibold">{attackInfo.attackInfo.type}</div>
            </div>
            <div>
              <div className="text-gray-400">Request Rate</div>
              <div className="text-red-400 font-semibold">
                {attackInfo.attackInfo.requestsPerSecond.toLocaleString()} req/s
              </div>
            </div>
            <div>
              <div className="text-gray-400">Threat Level</div>
              <div className={`font-semibold ${
                attackInfo.threat.threatLevel === 'HIGH' ? 'text-red-400' :
                attackInfo.threat.threatLevel === 'MEDIUM' ? 'text-yellow-400' :
                'text-green-400'
              }`}>
                {attackInfo.threat.threatLevel}
              </div>
            </div>
            <div>
              <div className="text-gray-400">Confidence</div>
              <div className="text-white font-semibold">{attackInfo.threat.ddosConfidence}%</div>
            </div>
          </div>
        </div>

        {/* AI Analysis Sections */}
        <div className="space-y-6">
          {/* Summary */}
          <Section title="📋 Attack Summary" content={analysis.summary} />

          {/* Motivation */}
          <Section title="🎯 Likely Motivation" content={analysis.motivation} />

          {/* Attack Vector */}
          <Section title="⚡ Attack Vector Analysis" content={analysis.vector} />

          {/* Geographic Context */}
          <Section title="🌍 Geographic Context" content={analysis.geographic} />

          {/* Threat Assessment */}
          <Section 
            title="⚠️ Threat Assessment" 
            content={analysis.assessment}
            highlight={attackInfo.threat.threatLevel === 'HIGH'}
          />

          {/* Risk Indicators */}
          {analysis.riskIndicators && analysis.riskIndicators.length > 0 && (
            <div className="bg-gray-800/50 rounded-lg p-4">
              <h3 className="text-lg font-semibold text-white mb-3">🔍 Risk Indicators</h3>
              <ul className="space-y-2">
                {analysis.riskIndicators.map((indicator: string, idx: number) => (
                  <li key={idx} className="flex items-start">
                    <span className="text-red-400 mr-2">•</span>
                    <span className="text-gray-300 text-sm">{indicator}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Mitigation */}
          <Section title="🛡️ Recommended Mitigation" content={analysis.mitigation} />
        </div>

        {/* Footer */}
        <div className="mt-6 pt-6 border-t border-gray-700 flex justify-between items-center">
          <div className="text-gray-400 text-xs">
            Generated by Gemini AI • {new Date().toLocaleString()}
          </div>
          <button
            onClick={onClose}
            className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg font-semibold transition"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

function Section({ title, content, highlight = false }: { title: string; content: string; highlight?: boolean }) {
  return (
    <div className={`rounded-lg p-4 ${highlight ? 'bg-red-900/20 border border-red-700' : 'bg-gray-800/50'}`}>
      <h3 className="text-lg font-semibold text-white mb-2">{title}</h3>
      <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">{content}</p>
    </div>
  );
}
